g_guide:
    - title: brand
      name: guide
      items:
          - title: color
            name: Color
          - title: font
            name: Typography
c_shuren:
    - title: summarize
      name: shuren
      items:
          - title: introduce
            name: introduction
    - title: component
      name: shuren
      groups:
          - title: mobile
            items:
                - title: button
                  name: button
                - title: picker
                  name: Picker
                - title: pickerTime
                  name: PickerTime
                - title: mobileTabs
                  name: mobileTabs
                
  
c_lanxinka:
    - title: summarize
      name: lanxinka
      items:
          - title: introduce
            name: introduction
    - title: component
      name: lanxinka
      groups:
          - title: mobile
            items:
                - title: button
                  name: button
